### ISSUE TITLE
Rename repository / org

### ISSUE THREAD

**Issue by mrocklin** [pydata/parallel-tutorial#12]
Currently this lives at mrocklin/parallel-data-analysis .  

Should we move this to a different org?  Perhaps we're ready to ask PyData to use their space?

Should we rename this?  `parallel-tutorial` perhaps?

@minrk @quasiben @ahmadia

**Comment by quasiben** [comment]
I think after PyCon moving to PyData makes sense.  I like the name parallel-tutorial a bit more.  I renamed my repo to [kubernetes-pydata-parallel](https://github.com/quasiben/kubernetes-pydata-parallel)

**Comment by mrocklin** [comment]
After or before pycon?  I suspect that links will remain valid

**Comment by quasiben** [comment]
Link will remain valid.   I would do it before PyCon

**Comment by mrocklin** [comment]
I'll wait a couple hours to see if anyone else has thoughts here and then check with the people that manage the PyData org

**Comment by minrk** [comment]
I like pydata/parallel-tutorial

**Comment by mrocklin** [comment]
I have a request out to someone at Continuum that I think has access to that org.  If anyone else knows somewhat with the ability to manage pydata repos please let me know.

**Comment by mrocklin** [comment]
@jreback do you have access to create repos on github.com/pydata ?

**Comment by mrocklin** [comment]
I've asked @aterrel to do this and he seems game

**Comment by aterrel** [comment]
I'm not an admin on this repo. I can move the code but the that loses the
issues and other metadata

**Comment by mrocklin** [comment]
@aterrel and I worked it out.  This repository is now moved.  Closing.  Thanks all!
